### DISCUSSION TITLE
gradient minimalist day ahead price

### DISCUSSION THREAD

**Discussion by CRdeGraaf** [JaccoR/hass-entso-e#140] [Graphs]
![image](https://github.com/JaccoR/hass-entso-e/assets/12608195/9f656a1e-a40d-48be-881f-69010f531f80)

```yaml
type: custom:apexcharts-card
graph_span: 2d
span:
  start: day
now:
  show: true
  label: Now
header:
  show: true
  show_states: true
  colorize_states: true
  title: LIVE Electricity price (cents €/kwh)
yaxis:
  - decimals: 2
    min: ~0
    max: ~40
    apex_config:
      title:
        text: Cents / kWh
experimental:
  color_threshold: true
series:
  - entity: sensor.average_electricity_price_today
    stroke_width: 2
    unit: ' cents / kWh'
    curve: stepline
    color_threshold:
      - value: 0
        color: '#28A745'
        opacity: 1
      - value: 15
        color: '#20C997'
        opacity: 1
      - value: 20
        color: '#17A2B8'
        opacity: 1
      - value: 30
        color: '#FFC107'
        opacity: 1
      - value: 40
        color: '#DC3545'
        opacity: 1
      - value: 70
        color: '#C82333'
        opacity: 1
      - value: 80
        color: '#891C24'
    float_precision: 1
    show:
      extremas: true
      header_color_threshold: true
    type: line
    data_generator: |
      return entity.attributes.prices.map((entry) => {
      return [new Date(entry.time), (entry.price * 100 + 15.4)];
      });
```
