### DISCUSSION TITLE
Norway: Fagne, including refund for private households

### DISCUSSION THREAD

**Discussion by toresetre** [JaccoR/hass-entso-e#161] [Price Modifyer Templates]
Bruker denne for Fagne, og regner med at den fungerer for andre nettleverandører med ligende modeller. 
Den tar ikke høyde for helligdager som faller på mandag til fredag.
Legger på merverdiavgift, nettleie, sertifikat og andre utgifter trekker fra eventuell strømstøtte

Trenger følgende entiteter:
input_number.strom_fagne_nettleie_natt_og_helg
input_number.strom_fagne_nettleie_ukedag_dagtid
input_number.strom_tibber_cert_og_tillegg
input_number.stromrefusjon_innslagsverdi (i 2024 er denne 73 øre før merverdiavgift)
input_number.stromrefusjon_prosentsats (i 2024 er denne 90 %)
sensor.kurs_eur

```yaml
  {% set s = {
      "hourly_fixed_cost": 0.0,
      "night": states('input_number.strom_fagne_nettleie_natt_og_helg') | float,
      "day": states('input_number.strom_fagne_nettleie_ukedag_dagtid') | float,
      "cert": states('input_number.strom_tibber_cert_og_tillegg') | float
    }
  %}
  {% set conversion_rate = states('sensor.kurs_eur') | float %}
  {% set current_price_nok = current_price * conversion_rate %}
  {% set base_price_vat = current_price_nok * 0.25 %}
  {% set refund_threshold = states('input_number.stromrefusjon_innslagsverdi') | float %}
  {% set refund_percent = states('input_number.stromrefusjon_prosentsats') | float %}
  {% set refund = 0 %}
  {% if current_price_nok > refund_threshold %}
    {% set refund = (current_price_nok - refund_threshold) * (refund_percent / 100) %}
  {% endif %}
  {% set net_day_cost = s.day + s.hourly_fixed_cost + s.cert - refund %}
  {% set net_night_cost = s.night + s.hourly_fixed_cost + s.cert - refund %}

  {% if now().isoweekday() >= 1 and now().isoweekday() <= 5 %}
    {% if now().hour >= 6 and now().hour < 22 %}
      {{ (base_price_vat + net_day_cost) | float(0) }}
    {% else %}
      {{ (base_price_vat + net_night_cost) | float(0) }}
    {% endif %}
  {% else %}
    {{ (base_price_vat + net_night_cost) | float(0) }}
  {% endif %}
```

```yaml
input_number:
  strom_fagne_nettleie_ukedag_dagtid:
    name: Nettleie Fagne ukedag dagtid
    min: 0
    max: 1
    step: 0.001
    icon: mdi:cash-lock
    unit_of_measurement: kr
  strom_fagne_nettleie_natt_og_helg:
    name: Nettleie Fagne natt og helg
    min: 0
    max: 1
    step: 0.001
    icon: mdi:cash-lock
    unit_of_measurement: kr
  strom_tibber_cert_og_tillegg:
    name: Tibber sertifikat og andre påslag
    min: 0
    max: 0.1
    step: 0.0005
    icon: mdi:cash-lock
    unit_of_measurement: kr
  stromrefusjon_innslagsverdi:
    name: Innslagsverdi Statens strømrefusjon
    min: 0
    max: 1
    step: 0.01
    icon: mdi:cash-lock
    unit_of_measurement: kr
  stromrefusjon_prosentsats:
    name: Prosentsats Statens strømrefusjon
    min: 0
    max: 100
    step: 1
    icon: mdi:percent
    unit_of_measurement: prosent
```

code for the currency stolen from stigvi:

```yml
    platform: rest
    resource: https://data.norges-bank.no/api/data/EXR/B.EUR.NOK.SP?lastNObservations=1&format=sdmx-json
    name: kurs_eur
    scan_interval: 43200
    unit_of_measurement: NOK
    value_template: "{{ value_json['data']['dataSets'][0]['series']['0:0:0:0']['observations']['0'][0] }}"
```
