### DISCUSSION TITLE
color graphs

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [JaccoR/hass-entso-e#27] [Graphs]
just a suggestion that might make the graph a bit more impactful, I've set some arbitrary colors in the experimental mode:

```
  - type: custom:apexcharts-card
    graph_span: 24h
    span:
      start: day
    now:
      show: true
      label: Now
    header:
      show: true
      title: Entso-e prijzen Vandaag (€/kwh)
    experimental:
      color_threshold: true

    series:
      - entity: sensor.entsoe_current_electricity_market_price
        color_threshold:
          - value: 0.05
            color: lightgreen
          - value: 0.1
            color: green
          - value: 0.15
            color: orange
          - value: 0.2
            color: darkorange
          - value: 0.25
            color: black
          - value: 0.3
            color: purple
          - value: 0.35
            color: maroon
          - value: 0.4
            color: red
        stroke_width: 2
        float_precision: 3
        type: column
        opacity: 1
```

<img width="521" alt="Schermafbeelding 2022-10-17 om 08 55 37" src="https://user-images.githubusercontent.com/33354141/196109274-9d6f08b4-9de6-46fa-9844-4ddcb39d08f7.png">

**Comment by ikke-zelf** [comment]
Great to see and thanks...
What even be more useful would be to have a percentage value. In that way you can color the bars compared against let's say the percentage of the average that day (cause not every day the min/max of that day is the same.)

**Reply by Mariusthvdb** [reply]
o that might be cool indeed. No clue yet how to try that in Apex though, I am not that savvy with the card yet.
Would you know how to do so?

**Reply by ikke-zelf** [reply]
I tried when the card was working before but did not yet succeed. am not sure if it's feasible.

**Comment by ikke-zelf** [comment]
> just a suggestion that might make the graph a bit more impactful, I've set some arbitrary colors in the experimental mode:
> 
> ```
>   - type: custom:apexcharts-card
>     graph_span: 24h
>     span:
>       start: day
>     now:
>       show: true
>       label: Now
>     header:
>       show: true
>       title: Entso-e prijzen Vandaag (€/kwh)
>     experimental:
>       color_threshold: true
> 
>     series:
>       - entity: sensor.entsoe_current_electricity_market_price
>         color_threshold:
>           - value: 0.05
>             color: lightgreen
>           - value: 0.1
>             color: green
>           - value: 0.15
>             color: orange
>           - value: 0.2
>             color: darkorange
>           - value: 0.25
>             color: black
>           - value: 0.3
>             color: purple
>           - value: 0.35
>             color: maroon
>           - value: 0.4
>             color: red
>         stroke_width: 2
>         float_precision: 3
>         type: column
>         opacity: 1
> ```
> 
> <img alt="Schermafbeelding 2022-10-17 om 08 55 37" width="521" src="https://user-images.githubusercontent.com/33354141/196109274-9d6f08b4-9de6-46fa-9844-4ddcb39d08f7.png">

where did you copy your code from? This due to the fact that the indentation is giving errors on my end if I copy it in the apex-chard card.

**Reply by ikke-zelf** [reply]
Also am I wondering how you get the prices for the hours to come as you don't use the data_generation part

**Reply by blowk** [reply]
The data generated part is used, but wasn't showed.

Here is the full example.

```
type: custom:apexcharts-card
graph_span: 24h
span:
  start: day
now:
  show: true
  label: Now
header:
  show: true
  title: Electriciteitsprijzen Vandaag (€/kwh)
experimental:
  color_threshold: true
series:
  - entity: sensor.current_electricity_market_price
    stroke_width: 2
    float_precision: 3
    type: column
    opacity: 1
    color: ''
    color_threshold:
      - value: 0.05
        color: lightgreen
      - value: 0.1
        color: green
      - value: 0.15
        color: orange
      - value: 0.2
        color: darkorange
      - value: 0.25
        color: black
      - value: 0.3
        color: purple
      - value: 0.35
        color: maroon
      - value: 0.4
        color: red
    data_generator: |
      return entity.attributes.prices_today.map((record, index) => {
        return [record.time, record.price];
      });
```
