### DISCUSSION TITLE
Help with apexcharts

### DISCUSSION THREAD

**Discussion by ThorAlex87** [JaccoR/hass-entso-e#30] [Q&A] [answered]
Hi! I'm pretty much a beginner, so bear with me. I've been using the nordpool integration for a while, but want to check out entso-e to see if it does a couple of things better. But before i start playing with the data i'd like to see it to make sure everything works right. I currently have this setup in apexcharts showing yesterdays, todays and tomorrows prices, and would like to do the same with entso-e so i can compare the data:

`series:
  - entity: sensor.nordpool_kwh_trheim_nok_3_095_025
    yaxis_id: Kr
    name: Pris
    curve: stepline
    extend_to: false
    float_precision: 3
    stroke_width: 2
    opacity: 0.4
    color: rgb(255,111,0)
  - entity: sensor.nordpool_kwh_trheim_nok_3_095_025
    yaxis_id: Kr
    name: Pris
    curve: stepline
    extend_to: false
    float_precision: 3
    stroke_width: 2
    opacity: 0.5
    color: rgb(2,93,136)
    data_generator: |
      return entity.attributes.raw_today.map((p) => {
        return [new Date(p.start), (new Date() > new Date(p.start)) ? null : p.value];
      });
  - entity: sensor.nordpool_kwh_trheim_nok_3_095_025
    yaxis_id: Kr
    name: Pris
    curve: stepline
    extend_to: false
    opacity: 0.5
    color: rgb(2,93,136)
    float_precision: 3
    stroke_width: 2
    data_generator: |
      return entity.attributes.raw_tomorrow.map((p) => {
        return [new Date(p.start), p.value];
      });`

I can make today work (partially anyways) with the example from the documentation, but i have no idea what to do with yesterday and tomorrow.

**Comment by JaccoR** [comment, marked as answer]
```
series:
  - entity: sensor.current_electricity_market_price
    stroke_width: 2
    float_precision: 3
    type: column
    opacity: 1
    color: ''
    data_generator: |
      return entity.attributes.prices_today.map((record, index) => {
        return [record.time, record.price];
      });
```

in the datagenerator you can change `entity.attributes.prices_today` to `entity.attributes.prices_tomorrow` or `entity.attributes.prices` for all available prices. Yesterdays data you can just show by using the current_price sensor as this records all prices up to the current time.

for your nordpool charts you can just change the `entity: sensor.nordpool_kwh_trheim_nok_3_095_025` to a entsoe entity and change the attributes to one of the three i mentioned above.

**Reply by ThorAlex87** [reply]
Thanks! Just changing the sensor and attribute does not seem to work, but when I copied your data generator I can make graphs for today and tomorrow. No data for yesterday yet, so that will be a problem for tomorrow. 

In the nordpool graph the color changes from blue for the future part of the graph to orrange in the past, with the changover following the "now" line. This does not work with the new graph. I'm guessing this has to do with the data generator for the today graph, but I can't figure out how put that functionality back.

Full apexcharts code with entso-e sensors:

```
header:
  show: true
  title: Strømpris nordpool
type: custom:apexcharts-card
yaxis:
  - id: Kr
    min: 0
    opposite: true
    decimals: 1
    apex_config:
      tickAmount: 5
      title:
        text: Pris
  - id: Kwt
    min: 0
    opposite: false
    decimals: 1
    apex_config:
      tickAmount: 5
      title:
        text: Forbruk
series:
  - entity: sensor.nordpool_kwh_trheim_nok_4_095_025
    yaxis_id: Kr
    name: Pris
    curve: stepline
    extend_to: false
    float_precision: 3
    stroke_width: 2
    opacity: 0.8
    color: rgb(255,111,0)
  - entity: sensor.nordpool_kwh_trheim_nok_4_095_025
    yaxis_id: Kr
    name: Pris
    curve: stepline
    extend_to: false
    float_precision: 3
    stroke_width: 2
    opacity: 1
    color: rgb(0,93,136)
    data_generator: |
      return entity.attributes.raw_today.map((p) => {
        return [new Date(p.start), (new Date() > new Date(p.start)) ? null : p.value];
      });
  - entity: sensor.nordpool_kwh_trheim_nok_4_095_025
    yaxis_id: Kr
    name: Pris
    curve: stepline
    extend_to: false
    opacity: 1
    color: rgb(0,93,136)
    float_precision: 3
    stroke_width: 2
    data_generator: |
      return entity.attributes.raw_tomorrow.map((p) => {
        return [new Date(p.start), p.value];
      });
now:
  show: true
graph_span: 3d
span:
  start: day
  offset: '-1d'
locale: nb
apex_config:
  chart:
    height: 300px
    zoom:
      enabled: true
    toolbar:
      show: true
      tools:
        zoom: true
        zoomin: false
        zoomout: false
        pan: false
        reset: true
  legend:
    show: false
    legend_value: false
  dataLabels:
    enabled: true
  xaxis:
    type: datetime
    labels:
      offsetX: 55
      offsetY: -5
      datetimeFormatter:
        month: ddd
        day: ddd
  tooltip:
    fixed:
      enabled: true
      position: bottomLeft
      hours_12: false

```
