### DISCUSSION TITLE
Gas prices

### DISCUSSION THREAD

**Discussion by Damazinho** [JaccoR/hass-entso-e#35] [General]
@Mariusthvdb Ik zie nu dat EasyEnergy toch wel grover afwijkingen dagelijk heeft in vergelijking met mijn nieuwe provider: EnergyZero.... Kun je daar hetzelfde trucje mee uithalen?

Api: https://api.energyzero.nl/v1/energyprices?fromDate=2022-10-20T22%3A00%3A00.000Z&tillDate=2022-10-21T21%3A59%3A59.999Z&interval=4&usageType=3&inclBtw=true

Zou eeuwig dankbaar zijn...

**Comment by Mariusthvdb** [comment]
ok je kunt dat als 
```
sensor:
  - platform: rest
    unique_id: energyzero_prices_rest
    name: Energyzero prices rest
    resource: https://api.energyzero.nl/v1/energyprices
    scan_interval: 900
    value_template: Ok
    params:
      fromDate: >
        {{(now().strftime('%Y-%m-%d')|as_datetime).isoformat()}}Z
      tillDate: >
        {{((now()+ timedelta(days=2)).strftime('%Y-%m-%d')|as_datetime).isoformat()}}Z
      interval: 4
      usageType: 3
      inclBtw: true
    json_attributes:
      - Prices
```

schrijven, en dan heb je een `sensor.energyzero_prices_rest` waarover je templates kunt maken als:

```
{{state_attr('sensor.energyzero_prices_rest','Prices')[27].price}}
```

Ik heb de resource even 2 dagen te meten vanaf 00:00:00 uur gegeven, omdat je even moet nadenken wanneer deze data wordt gevuld... is allemaal net niet helemaal zeker denk ik?

Als je zeker bent van de uren en dagen, dan kan je dat aanpassen natuurlijk.


Een andere mogelijkheid is om een `rest:` sensor te maken, zoals de andere die ik gepost heb for de gasprijzen van easy energy. Dus in het format:

```
rest:

  - resource: https://api.energyzero.nl/v1/energyprices
    scan_interval: 900
    params:
      fromDate: >
        {{(now().strftime('%Y-%m-%d')|as_datetime).isoformat()}}Z
      tillDate: >
        {{((now()+ timedelta(days=2)).strftime('%Y-%m-%d')|as_datetime).isoformat()}}Z
      interval: 4
      usageType: 3
      inclBtw: true

    sensor:

      - name: Gasprijs Energyzero uur 23
        value_template: >
          {{value_json.Prices[23].price}}
        json_attributes_path: "$.Prices[23]"
        json_attributes:
          - price # deze kan je natuurlijk weg laten, want is ook al de state (value_template)
          - readingDate
 ```


je kunt voor beide formats de andere uren gewoon maken door alleen de uren in de templates te wijzigen ;-) simpel....

met dank aan Mike Degatano (CentralCommand) in [Discord chat](https://discord.com/channels/330944238910963714/672223497736421388/1033452901462450208)

Always helping me out! thx Mike. @mdegat01
