### DISCUSSION TITLE
gradient graph yesterday, today, tomorrow

### DISCUSSION THREAD

**Discussion by ikke-zelf** [JaccoR/hass-entso-e#72] [Graphs]
After @katla50 posted a suggestion on how the graph could look like, I tried to make It as I would like it.
Still struggling to also get a consumed price per hour in a graph column bar, but for starters it's okay for now.
![image](https://user-images.githubusercontent.com/65031378/200194688-6919a5b2-19e7-43c9-a4af-c320c22a1adf.png)

**Comment by ikke-zelf** [comment]
````
type: custom:apexcharts-card
header:
  show: true
  title: Electriciteitsprijs (€/kwh) en verbruik
  show_states: true
  colorize_states: true
  standard_format: true
now:
  show: true
  color: rgb(0, 255, 0)
  label: Now
graph_span: 3d
span:
  start: day
  offset: '-1d'
apex_config:
  stroke:
    width: 2
  dataLabels:
    enabled: true
  fill:
    type: gradient
    gradient:
      shadeIntensity: 1
      inverseColors: false
      opacityFrom: 0.45
      opacityTo: 0.05
      stops:
        - 10
        - 50
        - 75
        - 1000
  legend:
    show: false
yaxis:
  - id: price
    decimals: 2
    show: true
  - id: usage
    show: true
    opposite: true
series:
  - entity: sensor.current_electricity_market_price
    yaxis_id: price
    extend_to: now
    name: Prijs gisteren
    unit: €/kwh
    float_precision: 3
    type: area
    curve: stepline
    color: lightblue
    show:
      legend_value: false
  - entity: sensor.average_electricity_price_today
    yaxis_id: price
    extend_to: now
    name: Prijs vandaag
    unit: €/kwh
    float_precision: 3
    type: area
    curve: stepline
    color: ''
    show:
      legend_value: false
    data_generator: |
      return entity.attributes.prices_today.map((record, index) => {
        return [record.time, record.price];
      });
  - entity: sensor.average_electricity_price_today
    yaxis_id: price
    extend_to: now
    name: Prijs morgen
    unit: €/kwh
    float_precision: 3
    type: area
    curve: stepline
    color: rgb(0,128,128)
    show:
      legend_value: false
    data_generator: |
      return entity.attributes.prices_tomorrow.map((record, index) => {
        return [record.time, record.price];
      });
  - entity: sensor.nuts_hourly_energy
    yaxis_id: usage
    unit: kw
    type: column
    stroke_width: 5
    name: Verbruik
    color: purple
    group_by:
      func: max
    show:
      legend_value: true

````

**Reply by jjtoard** [reply]
High,  Very nice graph.  Added it right away but my graph is missing the tomorrow part.  At the top it stays at N/A and no graph.

**Comment by katla50** [comment]
sorry for the bad formatting in my previous post, but here is my apexchart example that shows price and power consumption

![chart_power](https://user-images.githubusercontent.com/95768615/200230628-988d2d17-8916-448f-be34-86c0e629474d.png)

```
type: custom:apexcharts-card
header:
  show: true
  title: Strømpris og Forbruk
  show_states: true
  standard_format: true
now:
  show: true
  color: rgb(0, 255, 0)
graph_span: 3d
span:
  start: day
  offset: '-1d'
apex_config:
  stroke:
    width: 2
  dataLabels:
    enabled: true
  fill:
    type: gradient
    gradient:
      shadeIntensity: 1
      inverseColors: false
      opacityFrom: 0.45
      opacityTo: 0.05
      stops:
        - 10
        - 50
        - 75
        - 1000
  legend:
    show: false
  yaxis:
    - id: price
      show: true
      decimalsInFloat: 1
      floating: false
      forceNiceScale: true
      extend_to: end
    - id: usage
      show: true
      opposite: true
      decimalsInFloat: 1
      floating: false
      forceNiceScale: true
      extend_to: end
series:
  - entity: sensor.kjetil_current_electricity_market_price
    yaxis_id: price
    extend_to: now
    name: Pris NÅ
    unit: kr/kwt
    type: area
    curve: stepline
    color: tomato
    show:
      legend_value: false
  - entity: sensor.kjetil_average_electricity_price_today
    yaxis_id: price
    extend_to: now
    name: Pris slutt idag
    unit: kr/kwt
    type: area
    curve: stepline
    color: tomato
    show:
      legend_value: false
    data_generator: |
      return entity.attributes.prices_today.map((record, index) => {
         return [record.time, record.price];
       });
  - entity: sensor.kjetil_average_electricity_price_today
    yaxis_id: price
    extend_to: now
    name: Pris slutt imorgen
    unit: kr/kwt
    type: area
    curve: stepline
    color: tomato
    show:
      legend_value: false
    data_generator: |
      return entity.attributes.prices_tomorrow.map((record, index) => {
        return [record.time, record.price];
       });
  - entity: sensor.stromtime_utility
    yaxis_id: usage
    unit: kw
    type: column
    name: Forbruk Nå
    color: rgb(0,93,136)
    group_by:
      func: max
    show:
      legend_value: false


```
This is a modified chart from powersaver.no
