### DISCUSSION TITLE
Run script/automation at the moment of the lowest price

### DISCUSSION THREAD

**Discussion by cereal2nd** [JaccoR/hass-entso-e#76] [Q&A]
I want to run a script/automation the moment we reach the lowest prce of the day.
At this moment i would like to start charging my battery.

Any idea how to do this?

**Comment by maartenlandman89** [comment]
I have the same question. Can somone share his/here template/automation with us? I have a problem with how to use the entity with the time in a automation.

**Reply by MrOzzOnline** [reply]
You need to decide in what kind of timeframe you want to use to lowest price. I use the https://github.com/jpulakka/nordpool_diff integration where you can use the rank or interval option to look ahead at the next xx hours.

For example:
```
sensor:
  - platform: nordpool_diff
    entsoe_entity: sensor.injectie_current_electricity_market_price
    nordpool_entity: sensor.nordpool_kwh_be_eur_5_10_0
    filter_length: 3
    filter_type: interval
    unit: ''
    normalize: 'no'
```

This will give you a value for the current hour between -1 and 1 for the next 3 hours. This scales up to 20 hours.

I use 4 of them in different scenario's to trigger my EV charger and to display the current situation:
![image](https://user-images.githubusercontent.com/115424166/208429753-8b2ecd8c-c748-4456-a39d-25eac3ff8e4a.png)

**Reply by Hendrik12345678** [reply]
@MrOzzOnline 
can you share the configruation which one you made?
and which card you use?

**Reply by MrOzzOnline** [reply]
> @MrOzzOnline can you share the configruation which one you made? and which card you use?

Config using the nordpool_diff integration with is using both entseo and nordpool values for redundancy:

```
sensor:
  - platform: nordpool_diff
    entsoe_entity: sensor.injectie_current_electricity_market_price
    nordpool_entity: sensor.nordpool_kwh_be_eur_5_10_0
    filter_length: 3
    filter_type: interval
    unit: ''
    normalize: 'no'
  - platform: nordpool_diff
    entsoe_entity: sensor.injectie_current_electricity_market_price
    nordpool_entity: sensor.nordpool_kwh_be_eur_5_10_0
    filter_length: 6
    filter_type: interval
    unit: ''
    normalize: 'no'
  - platform: nordpool_diff
    entsoe_entity: sensor.injectie_current_electricity_market_price
    nordpool_entity: sensor.nordpool_kwh_be_eur_5_10_0
    filter_length: 12
    filter_type: interval
    unit: ''
    normalize: 'no'
  - platform: nordpool_diff
    entsoe_entity: sensor.injectie_current_electricity_market_price
    nordpool_entity: sensor.nordpool_kwh_be_eur_5_10_0
    filter_length: 20
    filter_type: interval
    unit: ''
    normalize: 'no'
```
Cards, standard vertical stack, grid and gauge:

```
type: vertical-stack
title: Huidige prijs t.o.v. komende uren (-1/1)
cards:
  - square: true
    columns: 4
    type: grid
    cards:
      - type: gauge
        entity: sensor.nordpool_diff_interval_3
        min: -1
        max: 1
        needle: true
        severity:
          green: 0.5
          yellow: 0
          red: -1
        name: 3 uur
      - type: gauge
        entity: sensor.nordpool_diff_interval_6
        min: -1
        max: 1
        needle: true
        severity:
          green: 0.5
          yellow: 0
          red: -1
        name: 6 uur
      - type: gauge
        entity: sensor.nordpool_diff_interval_12_2
        min: -1
        max: 1
        needle: true
        severity:
          green: 0.5
          yellow: 0
          red: -1
        name: 12 uur
      - type: gauge
        entity: sensor.nordpool_diff_interval_20
        min: -1
        max: 1
        needle: true
        severity:
          green: 0.6
          yellow: 0
          red: -1
        name: 20 uur
```

You can read up on the automation using node red here: https://community.home-assistant.io/t/ev-charging-scheduling-solution-with-solar-power-and-a-home-battery/482225
