### ISSUE TITLE
Sensors update erroneously at 1h at night instead of 14h.

### ISSUE THREAD

**Issue by ToonVanEyck** [JaccoR/hass-entso-e#135]
For the last two days, my `sensor.average_electricity_price_today` sensor has updated at 1h at night and populated the prices of tomorrow with the current lowest price. 

```
state_class: measurement
prices_today:
  - time: "2023-12-23 00:00:00+01:00"
    price: 0.10142
  - time: "2023-12-23 01:00:00+01:00"
    price: 0.09918
  - time: "2023-12-23 02:00:00+01:00"
    price: 0.09767
  - time: "2023-12-23 03:00:00+01:00"
    price: 0.09764
  - time: "2023-12-23 04:00:00+01:00"
    price: 0.09763
  - time: "2023-12-23 05:00:00+01:00"
    price: 0.09764
  - time: "2023-12-23 06:00:00+01:00"
    price: 0.09775
  - time: "2023-12-23 07:00:00+01:00"
    price: 0.10552
  - time: "2023-12-23 08:00:00+01:00"
    price: 0.11884
  - time: "2023-12-23 09:00:00+01:00"
    price: 0.14225
  - time: "2023-12-23 10:00:00+01:00"
    price: 0.14093
  - time: "2023-12-23 11:00:00+01:00"
    price: 0.14067
  - time: "2023-12-23 12:00:00+01:00"
    price: 0.14031
  - time: "2023-12-23 13:00:00+01:00"
    price: 0.13722
  - time: "2023-12-23 14:00:00+01:00"
    price: 0.13931
  - time: "2023-12-23 15:00:00+01:00"
    price: 0.1357
  - time: "2023-12-23 16:00:00+01:00"
    price: 0.14189
  - time: "2023-12-23 17:00:00+01:00"
    price: 0.14002
  - time: "2023-12-23 18:00:00+01:00"
    price: 0.14973
  - time: "2023-12-23 19:00:00+01:00"
    price: 0.14803
  - time: "2023-12-23 20:00:00+01:00"
    price: 0.13276
  - time: "2023-12-23 21:00:00+01:00"
    price: 0.1289
  - time: "2023-12-23 22:00:00+01:00"
    price: 0.11915
  - time: "2023-12-23 23:00:00+01:00"
    price: 0.10593
prices_tomorrow:
  - time: "2023-12-24 00:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 01:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 02:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 03:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 04:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 05:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 06:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 07:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 08:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 09:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 10:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 11:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 12:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 13:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 14:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 15:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 16:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 17:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 18:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 19:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 20:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 21:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 22:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 23:00:00+01:00"
    price: 0.09764
prices:
  - time: "2023-12-23 00:00:00+01:00"
    price: 0.10142
  - time: "2023-12-23 01:00:00+01:00"
    price: 0.09918
  - time: "2023-12-23 02:00:00+01:00"
    price: 0.09767
  - time: "2023-12-23 03:00:00+01:00"
    price: 0.09764
  - time: "2023-12-23 04:00:00+01:00"
    price: 0.09763
  - time: "2023-12-23 05:00:00+01:00"
    price: 0.09764
  - time: "2023-12-23 06:00:00+01:00"
    price: 0.09775
  - time: "2023-12-23 07:00:00+01:00"
    price: 0.10552
  - time: "2023-12-23 08:00:00+01:00"
    price: 0.11884
  - time: "2023-12-23 09:00:00+01:00"
    price: 0.14225
  - time: "2023-12-23 10:00:00+01:00"
    price: 0.14093
  - time: "2023-12-23 11:00:00+01:00"
    price: 0.14067
  - time: "2023-12-23 12:00:00+01:00"
    price: 0.14031
  - time: "2023-12-23 13:00:00+01:00"
    price: 0.13722
  - time: "2023-12-23 14:00:00+01:00"
    price: 0.13931
  - time: "2023-12-23 15:00:00+01:00"
    price: 0.1357
  - time: "2023-12-23 16:00:00+01:00"
    price: 0.14189
  - time: "2023-12-23 17:00:00+01:00"
    price: 0.14002
  - time: "2023-12-23 18:00:00+01:00"
    price: 0.14973
  - time: "2023-12-23 19:00:00+01:00"
    price: 0.14803
  - time: "2023-12-23 20:00:00+01:00"
    price: 0.13276
  - time: "2023-12-23 21:00:00+01:00"
    price: 0.1289
  - time: "2023-12-23 22:00:00+01:00"
    price: 0.11915
  - time: "2023-12-23 23:00:00+01:00"
    price: 0.10593
  - time: "2023-12-24 00:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 01:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 02:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 03:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 04:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 05:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 06:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 07:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 08:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 09:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 10:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 11:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 12:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 13:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 14:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 15:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 16:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 17:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 18:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 19:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 20:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 21:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 22:00:00+01:00"
    price: 0.09764
  - time: "2023-12-24 23:00:00+01:00"
    price: 0.09764
unit_of_measurement: €/kWh
attribution: Data provided by ENTSO-e Transparency Platform
device_class: monetary
icon: mdi:currency-eur
friendly_name: Average electricity price today
```

![Screenshot_2023-12-23-11-08-21-70_c3a231c25ed346e59462e84656a70e50](https://github.com/JaccoR/hass-entso-e/assets/24410099/12abe280-f339-48d2-84f6-c8ae2cb0010d)
![Screenshot_2023-12-23-11-08-44-02_c3a231c25ed346e59462e84656a70e50](https://github.com/JaccoR/hass-entso-e/assets/24410099/c830fb5b-c1fa-416e-ba61-3b2c0394f28c)
