### ISSUE TITLE
Wrong date/time in average_electricity_price_today

### ISSUE THREAD

**Issue by dirkschaap** [JaccoR/hass-entso-e#144]
Since the 18th of january, the dates of the attributes of the entity 'sensor.average_electricity_price_today' are fixed and don't change anymore:
 
![entsoe](https://github.com/JaccoR/hass-entso-e/assets/19284236/9863c149-b426-4056-b502-faf6a0475801)

Does anyone have a suggestion?

**Comment by NvdMeer** [comment]
I hsve the same problem since 26th februari

**Comment by vkanev** [comment]
Same here, latest date is 03-03-2024.

**Comment by VictorSchonk** [comment]
I got this issue since 12th of feb 2024.

**Comment by VictorvandenHoven** [comment]
I have this issue since 11th of march 2024:

```
state_class: measurement
unit_of_measurement: €/kWh
device_class: monetary
icon: mdi:currency-eur
friendly_name: Average electricity price today (Zonneplan)
prices_today:
  - time: "2024-03-11 00:00:00+01:00"
    price: 0.25134
  - time: "2024-03-11 01:00:00+01:00"
    price: 0.25231
  - time: "2024-03-11 02:00:00+01:00"
    price: 0.25577
  - time: "2024-03-11 03:00:00+01:00"
    price: 0.2511
  - time: "2024-03-11 04:00:00+01:00"
    price: 0.24517
  - time: "2024-03-11 05:00:00+01:00"
    price: 0.24293
  - time: "2024-03-11 06:00:00+01:00"
    price: 0.26518
  - time: "2024-03-11 07:00:00+01:00"
    price: 0.27241
  - time: "2024-03-11 08:00:00+01:00"
    price: 0.27598
  - time: "2024-03-11 09:00:00+01:00"`
```
