### ISSUE TITLE
Add `get_energy_prices` service call

### ISSUE THREAD

**Issue by TheFes** [JaccoR/hass-entso-e#147]
**Is your feature request related to a problem? Please describe.**
I am the author of the [cheapest_energy_hours macro](<https://github.com/TheFes/cheapest-energy-hours>) which can be used to determine eg the best time to turn on your dishwasher.
However, if you want to turn it on overnight, you loose today's data at midnight (as it will become yesterdays data then).

Some core integrations, like [easyEnergy](<https://www.home-assistant.io/integrations/easyenergy/#service-easyenergyget_energy_usage_prices>) provide a service call in which you can get the data for the period you want, including historical data.

**Describe the solution you'd like**
Add support for the service call mentioned above

**Describe alternatives you've considered**
Add an additional attribute with the data of yesterday.

**Additional context**
NA

**Comment by Roeland54** [comment]
The beta version of v0.5.0 does contain a "get_energy_prices" action. https://github.com/JaccoR/hass-entso-e/releases/tag/v0.5.0-beta1
Can you test and provide feedback?

**Comment by TheFes** [comment]
Nice, I will test!

**Comment by TheFes** [comment]
Works great. Tested it using this template sensor:
```yaml
- trigger:
    - platform: time_pattern
      hours: "/1"
    - platform: homeassistant
      event: start
    - platform: event
      event_type: testerdetesttest
  action:
    - action: entsoe.get_energy_prices
      data:
        config_entry: 2100acc47af75f6227f0394476b6c322
        start: "{{ today_at() - timedelta(days=1) }}"
        end: "{{ today_at() + timedelta(days=2) }}"
      response_variable: prices
  sensor:
    - unique_id: 96147157-eca9-460c-b4cb-97165594e7a8
      name: ENTSOE prices
      state: "{{ prices.prices | selectattr('timestamp', '<=', now().strftime('%Y-%m-%dT%H:%M:%S+00:00')) | map(attribute='price') | list | last }}"
      attributes:
        prices: "{{ prices.prices }}"
```
This will give a sensor with a prices attribute with the prices of yesterday, today and tomorrow (if available).
