### ISSUE TITLE
Feature request: configuration.yaml support

### ISSUE THREAD

**Issue by JaccoR** [JaccoR/hass-entso-e#18]
Quoting @jpulakka:
> The one-line input textfield isn't exactly optimal for holding a 30+ line template. I wonder what's the HASS philosophy for stuff like this. In the nordpool plugin I used to put everything in configuration.yaml, which is convenient to store in version control and it's clear where the data is.

There should be support for a configuration in yaml. The template for the configuration should look something like this:

```
sensor:
  - platform: entsoe
    api_key: <YOUR API KEY>
    area: "NL"
    additional_costs: "{{0.0|float}}" #default value
```
