### ISSUE TITLE
No values for tomorrow, prices attribute contains data from yesterday

### ISSUE THREAD

**Issue by ErwinP** [JaccoR/hass-entso-e#215]
Hi, 

I'm sorry if this issue has been reported before, but I couldn't find back a solution. It seems that the integration is not fetching the prices for tomorrow.

It has been installed using the API key, area "Belgium" and calculation_mode "rotation". On December 12th, The sensor `sensor.average_electricity_price`  has the following attributes:
```
state_class: measurement
unit_of_measurement: €/kWh
icon: mdi:currency-eur
friendly_name: Average electricity price
prices_today:
  - time: "2024-12-12 00:00:00+01:00"
    price: 0.12224
  - time: "2024-12-12 01:00:00+01:00"
    price: 0.1153
  - time: "2024-12-12 02:00:00+01:00"
    price: 0.10996
  - time: "2024-12-12 03:00:00+01:00"
    price: 0.10735
  - time: "2024-12-12 04:00:00+01:00"
    price: 0.11251
  - time: "2024-12-12 05:00:00+01:00"
    price: 0.12204
  - time: "2024-12-12 06:00:00+01:00"
    price: 0.15017
  - time: "2024-12-12 07:00:00+01:00"
    price: 0.25804
  - time: "2024-12-12 08:00:00+01:00"
    price: 0.38915
  - time: "2024-12-12 09:00:00+01:00"
    price: 0.4
  - time: "2024-12-12 10:00:00+01:00"
    price: 0.36337
  - time: "2024-12-12 11:00:00+01:00"
    price: 0.32883
  - time: "2024-12-12 12:00:00+01:00"
    price: 0.29307
  - time: "2024-12-12 13:00:00+01:00"
    price: 0.31855
  - time: "2024-12-12 14:00:00+01:00"
    price: 0.35289
  - time: "2024-12-12 15:00:00+01:00"
    price: 0.47591
  - time: "2024-12-12 16:00:00+01:00"
    price: 0.551
  - time: "2024-12-12 17:00:00+01:00"
    price: 0.56546
  - time: "2024-12-12 18:00:00+01:00"
    price: 0.43307
  - time: "2024-12-12 19:00:00+01:00"
    price: 0.37503
  - time: "2024-12-12 20:00:00+01:00"
    price: 0.24161
  - time: "2024-12-12 21:00:00+01:00"
    price: 0.1694
  - time: "2024-12-12 22:00:00+01:00"
    price: 0.15
  - time: "2024-12-12 23:00:00+01:00"
    price: 0.13475
prices_tomorrow: []
prices:
  - time: "2024-12-11 01:00:00+01:00"
    price: 0.10412
  - time: "2024-12-11 02:00:00+01:00"
    price: 0.10197
  - time: "2024-12-11 03:00:00+01:00"
    price: 0.10035
  - time: "2024-12-11 04:00:00+01:00"
    price: 0.0982
  - time: "2024-12-11 05:00:00+01:00"
    price: 0.10703
  - time: "2024-12-11 06:00:00+01:00"
    price: 0.1164
  - time: "2024-12-11 07:00:00+01:00"
    price: 0.1496
  - time: "2024-12-11 08:00:00+01:00"
    price: 0.235
  - time: "2024-12-11 09:00:00+01:00"
    price: 0.26188
  - time: "2024-12-11 10:00:00+01:00"
    price: 0.23714
  - time: "2024-12-11 11:00:00+01:00"
    price: 0.24105
  - time: "2024-12-11 12:00:00+01:00"
    price: 0.24404
  - time: "2024-12-11 13:00:00+01:00"
    price: 0.24473
  - time: "2024-12-11 14:00:00+01:00"
    price: 0.26633
  - time: "2024-12-11 15:00:00+01:00"
    price: 0.28452
  - time: "2024-12-11 16:00:00+01:00"
    price: 0.31969
  - time: "2024-12-11 17:00:00+01:00"
    price: 0.3489
  - time: "2024-12-11 18:00:00+01:00"
    price: 0.31002
  - time: "2024-12-11 19:00:00+01:00"
    price: 0.27835
  - time: "2024-12-11 20:00:00+01:00"
    price: 0.18666
  - time: "2024-12-11 21:00:00+01:00"
    price: 0.1611
  - time: "2024-12-11 22:00:00+01:00"
    price: 0.15
  - time: "2024-12-11 23:00:00+01:00"
    price: 0.13602
  - time: "2024-12-12 00:00:00+01:00"
    price: 0.12224
  - time: "2024-12-12 01:00:00+01:00"
    price: 0.1153
  - time: "2024-12-12 02:00:00+01:00"
    price: 0.10996
  - time: "2024-12-12 03:00:00+01:00"
    price: 0.10735
  - time: "2024-12-12 04:00:00+01:00"
    price: 0.11251
  - time: "2024-12-12 05:00:00+01:00"
    price: 0.12204
  - time: "2024-12-12 06:00:00+01:00"
    price: 0.15017
  - time: "2024-12-12 07:00:00+01:00"
    price: 0.25804
  - time: "2024-12-12 08:00:00+01:00"
    price: 0.38915
  - time: "2024-12-12 09:00:00+01:00"
    price: 0.4
  - time: "2024-12-12 10:00:00+01:00"
    price: 0.36337
  - time: "2024-12-12 11:00:00+01:00"
    price: 0.32883
  - time: "2024-12-12 12:00:00+01:00"
    price: 0.29307
  - time: "2024-12-12 13:00:00+01:00"
    price: 0.31855
  - time: "2024-12-12 14:00:00+01:00"
    price: 0.35289
  - time: "2024-12-12 15:00:00+01:00"
    price: 0.47591
  - time: "2024-12-12 16:00:00+01:00"
    price: 0.551
  - time: "2024-12-12 17:00:00+01:00"
    price: 0.56546
  - time: "2024-12-12 18:00:00+01:00"
    price: 0.43307
  - time: "2024-12-12 19:00:00+01:00"
    price: 0.37503
  - time: "2024-12-12 20:00:00+01:00"
    price: 0.24161
  - time: "2024-12-12 21:00:00+01:00"
    price: 0.1694
  - time: "2024-12-12 22:00:00+01:00"
    price: 0.15
  - time: "2024-12-12 23:00:00+01:00"
    price: 0.13475
attribution: Data provided by ENTSO-e Transparency Platform
```
While `today` contains the correct data, `tomorrow` is empty, and `prices` contain the data from the day before. I'm on HA version `2024.12.1` and version `0.6.3` of this integration.

Thank you in advance for taking a look at this, and don't hesitate if more information is required!
