### ISSUE TITLE
no data

### ISSUE THREAD

**Issue by dieginvj** [JaccoR/hass-entso-e#230]
I don't receive prices in home assistant

**Comment by M66B** [comment]
> I don't receive prices in home assistant

I have the same. Which home assistant version are you using?

**Comment by CWILDMOUNTAIN** [comment]
same here

**Comment by schellekensonline** [comment]
Same here entity is unavailable. Using an updated HA core

**Comment by dieginvj** [comment]
2025.4 version of homesssistant is what I use. 
Problem was there just before the update. I re-installed the addon but didn’t help.

**Comment by TheBrankman** [comment]
Maybe it is a problem again with the entso-e website itself, some days ago?
I don't know if I am looking through the right link, but when looking at the day ahead prices I get "incomplete data" and "not available"

[https://m-transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=true&viewType=GRAPH&areaType=BZN&atch=false&dateTime.dateTime=04.04.2025+00:00|UTC|DAY&dateTime.timezone=UTC&dateTime.timezone_input=UTC&biddingZone.values=CTY|10YAL-KESH-----5!BZN|10YAL-KESH-----5&resolution.values=PT60M](url)

**Comment by dmutsaers** [comment]
Prices are missing from entso-e too.

**Comment by RvV1979** [comment]
Thanks for looking into this. In my opinion, this is happening way too often for the ENTSO-e service to be a reliable source of information.

**Comment by TheBrankman** [comment]
> Thanks for looking into this. In my opinion, this is happening way too often for the ENTSO-e service to be a reliable source of information.

I agree.... I tried also the EnergyZero integration and it seems to have less problema, but I miss the  nice graphs in lovelace.
Another advantage, it has also tha gas prices

**Comment by MEOoms** [comment]
same problem here: Unable to update entity 'sensor.marcel_ooms_next_hour_electricity_market_price', value: None and error: datetime.datetime(2025, 4, 4, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Amsterdam')), data: {datetime.datetime(2025, 4, 2, 0, 0,

**Comment by lancer73** [comment]
If you want to have a nice graph from EnergyZero, you can set a sensor template with this config:
```
template:
  - trigger:
    - trigger: time_pattern 
      hours: /1
    action:
      - action: energyzero.get_energy_prices
        data:
          incl_vat: true
          config_entry: [TO GET YOUR CONFIG ENTRY, RUN THE ACTION FROM THE DEVELOPMENT DASHBOARD AND LOOT AT THE GENERATED YAML] 
        response_variable: energyprices
    sensor:
      name: Energieprijzen
      unique_id: energieprijzen_constructed
      icon: mdi:cash
      unit_of_measurement: "Eur/kWh"
      state: >
        {{ states("sensor.energyzero_today_energy_current_hour_price")|float(default=100.0) }}
      attributes:                 
        prices: >
          {{ energyprices['prices'] }}
```

**Comment by TheBrankman** [comment]
> sensor.energyzero_today_energy_current



> If you want to have a nice graph from EnergyZero, you can set a sensor template with this config:
> 
> ```
> template:
>   - trigger:
>     - trigger: time_pattern 
>       hours: /1
>     action:
>       - action: energyzero.get_energy_prices
>         data:
>           incl_vat: true
>           config_entry: [TO GET YOUR CONFIG ENTRY, RUN THE ACTION FROM THE DEVELOPMENT DASHBOARD AND LOOT AT THE GENERATED YAML] 
>         response_variable: energyprices
>     sensor:
>       name: Energieprijzen
>       unique_id: energieprijzen_constructed
>       icon: mdi:cash
>       unit_of_measurement: "Eur/kWh"
>       state: >
>         {{ states("sensor.energyzero_today_energy_current_hour_price")|float(default=100.0) }}
>       attributes:                 
>         prices: >
>           {{ energyprices['prices'] }}
> ```

Tnx!
But I think, that is a graph of the past prices, not the day-ahead prices, am I right?

**Comment by PvaI** [comment]
Epexspot.com has tomorrow's data, entso hasn't for 24 hours. The others will probably update in the next hour or so: 

![Image](https://github.com/user-attachments/assets/1a3bf43e-642e-4dc3-b89f-4f4bb58e35b6)

**Comment by lancer73** [comment]
> > sensor.energyzero_today_energy_current
> 
> > If you want to have a nice graph from EnergyZero, you can set a sensor template with this config:
> > ```
> > template:
> >   - trigger:
> >     - trigger: time_pattern 
> >       hours: /1
> >     action:
> >       - action: energyzero.get_energy_prices
> >         data:
> >           incl_vat: true
> >           config_entry: [TO GET YOUR CONFIG ENTRY, RUN THE ACTION FROM THE DEVELOPMENT DASHBOARD AND LOOT AT THE GENERATED YAML] 
> >         response_variable: energyprices
> >     sensor:
> >       name: Energieprijzen
> >       unique_id: energieprijzen_constructed
> >       icon: mdi:cash
> >       unit_of_measurement: "Eur/kWh"
> >       state: >
> >         {{ states("sensor.energyzero_today_energy_current_hour_price")|float(default=100.0) }}
> >       attributes:                 
> >         prices: >
> >           {{ energyprices['prices'] }}
> > ```
> 
> Tnx! But I think, that is a graph of the past prices, not the day-ahead prices, am I right?

It is at least today's prices. Let's see how this behaves after 16:00 for tomorrows prices.

**Comment by TheBrankman** [comment]
> TO GET YOUR CONFIG ENTRY, RUN THE ACTION FROM THE DEVELOPMENT DASHBOARD AND LOOT AT THE GENERATED YAML

Oh and can you please explain this line:
TO GET YOUR CONFIG ENTRY, RUN THE ACTION FROM THE DEVELOPMENT DASHBOARD AND LOOT AT THE GENERATED YAML

How do I have to do that?

**Comment by lancer73** [comment]
> > TO GET YOUR CONFIG ENTRY, RUN THE ACTION FROM THE DEVELOPMENT DASHBOARD AND LOOT AT THE GENERATED YAML
> 
> Oh and can you please explain this line:
> TO GET YOUR CONFIG ENTRY, RUN THE ACTION FROM THE DEVELOPMENT DASHBOARD AND LOOT AT THE GENERATED YAML
> 
> How do I have to do that?
>  

Go to development tools dashboard, select "actions", select action "EnergyZero: Get Energy Prices", select "Config Entry", "Go to Yaml mode" at the bottom and copy the config entry key.

**Comment by PvaI** [comment]
energyzero just updated 👍

**Comment by TheBrankman** [comment]
> energyzero just updated 👍

Okay, I get the prices of today and also the apex graph.
But it seems to have an offset of 2 hours, so I have to look into that.
And the prices for 24h to 48h are not downloaded....

**Comment by lancer73** [comment]
> > energyzero just updated 👍
> 
> Okay, I get the prices of today and also the apex graph.
> But it seems to have an offset of 2 hours, so I have to look into that.
> And the prices for 24h to 48h are not downloaded....

Date is in utc, hence the 2 hour offset. Now playing with templates for start and ent time to get tomorrow as well.

**Comment by jee67** [comment]
Problem on Entso platform:
[https://transparency.entsoe.eu/news/widget?id=67efb3a4a2a7b927aeb0e4ef](url)

**Comment by lancer73** [comment]
> > energyzero just updated 👍
> 
> Okay, I get the prices of today and also the apex graph. But it seems to have an offset of 2 hours, so I have to look into that. And the prices for 24h to 48h are not downloaded....

This will give you todays and tomorrows prices:
```
template:                                                                  
  - trigger:                                                               
    - trigger: time_pattern                                                
      hours: /1                                                            
    action:                                                                
      - action: energyzero.get_energy_prices                               
        data:                                                              
          incl_vat: true                                                   
          config_entry: [YOU CONFIG ENTRY HERE]                   
          start: >                                                         
            {{ now().strftime("%Y-%m-%d") }} 00:00:00                      
          end: >                                                           
            {{ ((now()|as_timestamp + 86400)|as_datetime).strftime("%Y-%m-%d") }} 23:59:00
        response_variable: energyprices                                                   
    sensor:                                                                               
      name: Energieprijzen                                                                
      unique_id: energieprijzen_constructed                                               
      icon: mdi:cash                                                       
      unit_of_measurement: "Eur/kWh"                                       
      state: >                                                             
        {{ states("sensor.energyzero_today_energy_current_hour_price")|float(default=100.0) }}
      attributes:                                                                             
        prices: >                                                                             
          {{ energyprices['prices'] }}    
```

**Comment by MEOoms** [comment]
Are the bare prices of all dutch providers based on the same data? In other words, can I use energyzero prices for nextenergy (taking into account differences in the standard, unchanging VAT and costs of course)?

**Comment by lancer73** [comment]
> Are the bare prices of all dutch providers based on the same data? In other words, can I use energyzero prices for nextenergy (taking into account differences in the standard, unchanging VAT and costs of course)?

They are close. There is some difference in handling cost (per kWh), but as far as I know all are based on EPEX. The handling cost should be published somewhere.

**Comment by TheBrankman** [comment]
> > You can check my chart above, all prices are the same before your provider’s added costs, most also provide the Epex price, although some include taxes and others exclude them, you need to look at the data to figure it and you can use the websites to do a calculation of your costs and the details will show their rates. Or check enerergievergelijk.nl -> dynamische contracten in the kennisbank.
> > At this time only ENTSO and Nordpool are missing data, EPEX was the first to have tomorrow’s data, the others soon followed.
> 
> For me Nordpool is working without any problem.
> 
> ![Image](https://github.com/user-attachments/assets/f599d6f2-b3e4-480a-acdd-3f0648e05306)

I also was changing to Nord Pool, and till now, it is working great! I now choose Nordpool because this one has also an addin in EVCC, and EnergyZero, I can not find there....

Only the gasprices, I take from EnergyZero....

I let Entso-e run in the background but don't use the sensors for now.... It stoos too often.....
Hopefully NordPool and/or EnergyZero are more reliable.

Hm, sorry, in the Entso-e thread we are now talking about how to use other energy integrations.....

**Comment by dmutsaers** [comment]
> I also was changing to Nord Pool, and till now, it is working great! I now choose Nordpool because this one has also an addin in EVCC, and EnergyZero, I can not find there....

Could you point me to a working Apex Chart template for Nord Pool? Thanks!

**Comment by M66B** [comment]
> > I also was changing to Nord Pool, and till now, it is working great! I now choose Nordpool because this one has also an addin in EVCC, and EnergyZero, I can not find there....
> 
> Could you point me to a working Apex Chart template for Nord Pool? Thanks!

https://www.creatingsmarthome.com/index.php/2022/09/17/home-assistant-nord-pool-spot-prices-and-how-to-automate-devices-for-cheapest-hours/

Note that you need to use the custom Nordpool intergation for this:

https://github.com/custom-components/nordpool

**Comment by jee67** [comment]
> > > I also was changing to Nord Pool, and till now, it is working great! I now choose Nordpool because this one has also an addin in EVCC, and EnergyZero, I can not find there....
> > 
> > 
> > Could you point me to a working Apex Chart template for Nord Pool? Thanks!
> 
> https://www.creatingsmarthome.com/index.php/2022/09/17/home-assistant-nord-pool-spot-prices-and-how-to-automate-devices-for-cheapest-hours/
> 
> Note that you need to use the custom Nordpool intergation for this:
> 
> https://github.com/custom-components/nordpool

I think Nordpool is quite reliable. I’m using the cheapest hours script for about 1,5 years now to control one of hour hot water boilers. It’s turned on and off during cheapest hours.

**Comment by Fidelity88** [comment]
Still no data from ENTSOE :( Same with EVCC

**Comment by lemonheadgit** [comment]
Workaround that gave some result is to change (toggle) the country (Area) in the API configuration (Integration)

**Comment by rocar13** [comment]
Is it still down?

**Comment by martin3000** [comment]
There is data for 15 minute intervals, but not for the 60 min. intervals.

**Comment by IJsbeer-NL** [comment]
> I don't receive prices in home assistant

I see on the ENTSO site that they are updating their services. Could it be that the endpoint in the code needs to be updated?
Is some one mainting this piece of code ?

**Comment by jee67** [comment]
Starting 0:00 CET last night entso provides data again.

**Comment by IJsbeer-NL** [comment]
> Starting 0:00 CET last night entso provides data again.

Oh yes, the update must be completed. Thanks for updating us. ;-)

**Comment by martin3000** [comment]
> Starting 0:00 CET last night entso provides data again.

The PT60M interval is present only for today.

**Comment by schellekensonline** [comment]
> > I also was changing to Nord Pool, and till now, it is working great! I now choose Nordpool because this one has also an addin in EVCC, and EnergyZero, I can not find there....
> 
> Could you point me to a working Apex Chart template for Nord Pool? Thanks!

Use this template sensor and you can use the same APEX chart config as before

```YAML
  - trigger:
    - trigger: time_pattern
      hours: /1
    action:
      - action: nordpool.get_prices_for_date
        response_variable: energyprices
        data:
          config_entry: [GET FROM DEVELOPER TOOLS/ACTIONS]
          date: "{{ now().date() + timedelta(days=0) }}"
          areas: NL
          currency: EUR
    sensor:
      name: Nord pool NL current prices Excluding Tax
      unique_id: nord_pool_nl_current_prices_excluding_tax
      unit_of_measurement: "€/kWh"
      state: >
        {% set energy_prices = energyprices['NL'] %}
        {{ (energy_prices[now().hour]['price'] | float(0)) / 1000 }}
      attributes:
        prices: >
          {% set energy_prices = energyprices['NL'] %}
          {% set ns = namespace(list=[]) %}
          {% for i in range(energy_prices|length) %}
          {%   set ns.list = ns.list+[{'time': energy_prices[i]['start'], 'price':((energy_prices[i]['price'])/1000)}] %}  
          {% endfor %}
          {{ ns.list }}
```
